layout_spectrum: 0.7987106507644057
typography_spectrum: 0.7258256587665528
color:
  brandStrength: 0.6609336328692734
  lightness: 0.5726763138081878
  saturation: 0.2840657979249954
  rhythmicContrast: 0.7163972479756922
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
name: LifeImprovements
navigation:
  - name: Find out how you fit in Your Relationship
    url: 'http://www.energeticawesomeness.com/'
    type: external
description: It Always works
